name: Canonical docs rules
author: '@evilnick'
description: 'Installs Vale rules from the Canonical documentation style guide.'
inputs:
  vale-config:  
    description: 'path/to/vale.ini to use'
    required: true
    default: './vale.ini'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: check Vale config
      env:
          TEMP_DIR: ${{ runner.temp }}
          ACTION_DIR: ${{ github.action_path }}
      run: |
        if ! test -f ./vale.ini; then
        echo "No vale.ini found, using default"
        cp $ACTION_DIR/vale.ini .
        sed  -i "s:./styles:$TEMP_DIR/styles:" vale.ini 
        fi
        mkdir $TEMP_DIR/styles
        cp -r $ACTION_DIR/styles $TEMP_DIR/styles
        echo "Styles copied to $TEMP_DIR"
        cat vale.ini
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
